# Generated by Django 2.1.7 on 2019-03-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_auto_20190315_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='collection_id',
            new_name='face_id',
        ),
        migrations.RenameField(
            model_name='userextension',
            old_name='contacts_collection',
            new_name='contacts_collection_id',
        ),
    ]
